Prerequisities of certmagic requires golang=<1.14
Error: hello.SupportsCertificate undefined (type *tls.ClientHelloInfo has no field or method SupportsCertificate)
Closed bugreport: https://github.com/caddyserver/xcaddy/issues/14

Golang dockerhub repo doesn't provide alpine3.10+golang1.14